import Header from "./Header.jsx"

const Post = ()=>{
    return(
    <>
    <Header/>
    <p style={{ width:"900px", textAlign:"center", alignItems:"center", margin:"auto"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Est dolores culpa corporis a qui earum veniam assumenda accusantium, debitis minus, suscipit, officia cum reiciendis. Ex optio facilis officiis sunt itaque ut maiores deleniti ipsa placeat illo iusto repellat animi iure et, illum nulla, amet exercitationem quasi at, accusamus porro quos excepturi. Tempora aliquam beatae harum quam minima explicabo assumenda sint, officiis quidem ut adipisci, consectetur expedita  ut voluptates vitae delectus accusantium odio officiis doloremque dolor ea aspernatur molestias aliquid possimus eum, perspiciatis doloribus atque. Dolore tenetur molestias quasi atque delectus odit, corrupti modi earum veritatis, aliquid consequuntur necessitatibus aut nisi quibusdam dolorum hic iusto esse sapiente quisquam pariatur. Quae doloremque non a repellendus optio at, incidunt, provident suscipit, et mollitia veniam. Magni voluptates atque omnis nihil aliquid nulla debitis earum doloremque assumenda necessitatibus. Temporibus, doloribus? Eaque est ipsum quo incidunt, repellendus tenetur? Cumque accusamus tenetur, corporis sequi harum ratione tempore voluptate quaerat numquam quis repudiandae autem rerum natus debitis, iure aliquam unde voluptatibus! Sunt quidem iste ratione explicabo odio eum saepe voluptas odit praesentium, quisquam error excepturi blanditiis quibusdam fugit repellat cumque debitis placeat quia ipsam, quam incidunt perspiciatis obcaecati consequuntur culpa? Nihil libero odio vel maxime impedit, ut nisi culpa blanditiis, dolor enim, quaerat explicabo! Cumque impedit soluta nulla esse iste ducimus, atque vitae ipsum veritatis autem officiis deleniti minus provident.</p>
    </>)
}
export default Post;